apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwtissuer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jwtissuer
  template:
    metadata:
      labels:
        app: jwtissuer
    spec:
      containers:
      - name: jwtissuer
        image: lucap9056/peergrine_jwtissuer:latest
        ports:
        - containerPort: 80
          name: client-http
        - containerPort: 50051
          name: service-grpc
        env:
        - name: APP_REDIS_ADDR
          value: redis:6379
        - name: APP_PULSAR_ADDRS
          value: pulsar://pulsar:6650
        - name: APP_PULSAR_TOPIC
          value: UnifiedMessage
        - name: APP_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APP_SERVICE_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
          
---

apiVersion: v1
kind: Service
metadata:
  name: jwtissuer
spec:
  ports:
  - name: client-http
    port: 80
    targetPort: 80
  - name: service-grpc
    port: 50051
    targetPort: 50051
  selector:
    app: jwtissuer
