apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtc-bridge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rtc-bridge
  template:
    metadata:
      labels:
        app: rtc-bridge
    spec:
      containers:
      - name: rtc-bridge
        image: lucap9056/peergrine_rtc-bridge:latest
        ports:
        - containerPort: 80
          name: client-http
        env:
        - name: APP_REDIS_ADDR
          value: redis:6379
        - name: APP_PULSAR_ADDRS
          value: pulsar://pulsar:6650
        - name: APP_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APP_SERVICE_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---

apiVersion: v1
kind: Service
metadata:
  name: rtc-bridge
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rtc-bridge
