// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: unifiedmessage.proto

package unifiedmessage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UnifiedMessage_SendMessage_FullMethodName = "/unifiedmessage.UnifiedMessage/SendMessage"
)

// UnifiedMessageClient is the client API for UnifiedMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnifiedMessageClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type unifiedMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewUnifiedMessageClient(cc grpc.ClientConnInterface) UnifiedMessageClient {
	return &unifiedMessageClient{cc}
}

func (c *unifiedMessageClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, UnifiedMessage_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnifiedMessageServer is the server API for UnifiedMessage service.
// All implementations must embed UnimplementedUnifiedMessageServer
// for forward compatibility.
type UnifiedMessageServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	mustEmbedUnimplementedUnifiedMessageServer()
}

// UnimplementedUnifiedMessageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUnifiedMessageServer struct{}

func (UnimplementedUnifiedMessageServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedUnifiedMessageServer) mustEmbedUnimplementedUnifiedMessageServer() {}
func (UnimplementedUnifiedMessageServer) testEmbeddedByValue()                        {}

// UnsafeUnifiedMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnifiedMessageServer will
// result in compilation errors.
type UnsafeUnifiedMessageServer interface {
	mustEmbedUnimplementedUnifiedMessageServer()
}

func RegisterUnifiedMessageServer(s grpc.ServiceRegistrar, srv UnifiedMessageServer) {
	// If the following call pancis, it indicates UnimplementedUnifiedMessageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UnifiedMessage_ServiceDesc, srv)
}

func _UnifiedMessage_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedMessageServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnifiedMessage_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedMessageServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UnifiedMessage_ServiceDesc is the grpc.ServiceDesc for UnifiedMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnifiedMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unifiedmessage.UnifiedMessage",
	HandlerType: (*UnifiedMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _UnifiedMessage_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unifiedmessage.proto",
}
